schema: "classroom50/repo-config/v1"
classroom: "swdevprac2-69-1"
assignment: "a10-swdevprac2-69-1"
secret: "cf2djm54"
owner:
  username: "pat21889"
  id: 79015913
  accepted_at: "2026-10-08T12:36:30Z"
source:
  owner: "SWDevPrac2-69-1"
  owner_id: 312147402
  repo: "2110507_a10_starter"
  branch: "main"
